/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-10-19 08:07:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch06;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shippingInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1664261832316L));
    _jspx_dependants.put("jar:file:/E:/A_TeachingMaterial/4.MiddleProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JSPBook/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/bootstrap.min.css\">\r\n");
      out.write("<title>배송 정보</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 머리글에 해당하는 menu.jsp 파일의 내용을 포함하도록\r\n");
      out.write("      include 액션 태그를 작성 -->\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("   <div class=\"jumbotron\">\r\n");
      out.write("      <!-- container : 이 안에 내용이 있다 -->\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <h1 class=\"display-3\">배송 정보</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- ---------배송 정보 시작--------- -->\r\n");
      out.write("   <!-- shippingInfo.jsp?cartId=91B0EBCC6253A00643673291FC85D447 -->\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("   \t\t<form action=\"processShippingInfo.jsp\" class=\"form-horizontal\" method=\"post\">\r\n");
      out.write("   \t\t\t<input type=\"hidden\" name=\"cartId\" value='");
      out.print(request.getParameter("cartId"));
      out.write("' />\r\n");
      out.write("   \t\t<div class=\"form-group row\">\r\n");
      out.write("   \t\t\t<label class=\"col-sm-2\">성명</label>\r\n");
      out.write("   \t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("   \t\t\t\t<input type=\"text\" name=\"name\" class=\"form-control\" required=\"required\" />\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<div class=\"form-group row\">\r\n");
      out.write("   \t\t\t<label class=\"col-sm-2\">배송일</label>\r\n");
      out.write("   \t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("   \t\t\t\t<input type=\"date\" name=\"shippingDate\" class=\"form-control\" required=\"required\" />(yyyy-mm-dd)\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<div class=\"form-group row\">\r\n");
      out.write("   \t\t\t<label class=\"col-sm-2\">국가명</label>\r\n");
      out.write("   \t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("   \t\t\t\t<input type=\"text\" name=\"country\" class=\"form-control\" required=\"required\" />\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<div class=\"form-group row\">\r\n");
      out.write("   \t\t\t<label class=\"col-sm-2\">우편번호</label>\r\n");
      out.write("   \t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("   \t\t\t\t<input type=\"text\" name=\"zipCode\" class=\"form-control\" required=\"required\" />\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<div class=\"form-group row\">\r\n");
      out.write("   \t\t\t<label class=\"col-sm-2\">주소</label>\r\n");
      out.write("   \t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("   \t\t\t\t<input type=\"text\" name=\"addressName\" class=\"form-control\" required=\"required\" />\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t<div class=\"form-group row\">\r\n");
      out.write("   \t\t\t<div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("   \t\t\t\t<a href=\"cart.jsp?cartId=");
      out.print(request.getParameter("cartId"));
      out.write("\" \r\n");
      out.write("   \t\t\t\t\tclass=\"btn btn-secondary\" role=\"button\">이전</a>\r\n");
      out.write("   \t\t\t\t<input type=\"submit\" class=\"btn btn-primary\" value=\"등록\" />\r\n");
      out.write("   \t\t\t\t<a href=\"checkOutCancelled.jsp\"\r\n");
      out.write("   \t\t\t\t\tclass=\"btn btn-secondary\" role=\"button\">취소</a>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t</div>\r\n");
      out.write("   \t\t</form>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- ---------배송 정보 끝--------- -->\r\n");
      out.write("   <!-- 끝맺음 -->\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
